<a href="https://colab.research.google.com/github/yongmin1004/2025-2-Discrete-MathMetics/blob/main/%5B05%5D%EA%B4%80%EA%B3%84_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

#1.이항 관계 연산
A = {1,2,3}
B = {2,3,4}
R = {(1,2),(2,3),(3,2),(3,4)}
print("관계R:",R)

In [1]:
#2. 관계 행렬 표현
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

A = {1,2,3}
B = {2,3,4}
R = {(1,2),(2,3),(3,2),(3,4)}

A_list = sorted(A)
B_list = sorted(B)

relation_matrix = np.zeros((len(A_list),len(B_list)),dtype = int)

for i , a in enumerate(A_list): #i = index a = value
  for j , b in enumerate(B_list):# j = index b = value
    if(a,b) in R:
      relation_matrix[i,j] = 1

print("관계 행렬(rows:A, columns:B):")
print(relation_matrix)


관계 행렬(rows:A, columns:B):
[[1 0 0]
 [0 1 0]
 [1 0 1]]


In [2]:
#3. 합성 관계 예제
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

#R: A->B
#S: B->C

A = {1,2,3}
B = {2,3,4}
C = {'x','y'}
R = {(1,2),(2,3),(3,2),(3,4)} #A -> B 로 향하는 관계 (a,b1)
S = {(2,'x'),(3,'y'),(4,'x')} #B -> C로 향하는 관계 (b2,c)

#합성관계 R.S
composed_relation = set()

for(a,b1) in R:
  for(b2,c) in S:
    if b1 == b2:
      composed_relation.add((a,c))

print("\n합성 관계 R.S:",composed_relation)


합성 관계 R.S: {(3, 'x'), (1, 'x'), (2, 'y')}
