<a href="https://colab.research.google.com/github/yongmin1004/2025-2-Discrete-MathMetics/blob/main/Linear_Algebra_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1. 파이썬 기초

print("Hello, World")

x = 3
print("정수: %01d, %02d, %03d, %04d, %05d" %(x,x,x,x,x))

x = 256.123
print("실수: %.0f, %.1f, %.2f" %(x,x,x))

x = "Hello Word"
print("문자열:[%s]" %(x))

#반복문, 조건문
contents = ["Regression", "Classification", "SVM", "Clustering","Dimension reduction","NN","CNN","AE","GAN","RNN"]
for con in contents:
  if con in ["Regression","Classification","SVM","Clustering","Dimension Reduction"]:
    print("%s 은(는) 기계학습 내용입니다" %con)

  elif con in ["CNN"]:
    print("%s 은(는) convolutional neural network 입니다" %con)

  else:
    print("%s 은(는) 심측학습 내용입니다" %con)

#반복문과 인덱스
for(i,con) in enumerate(contents):
  print("[%d/%d] : %s"%(i,len(contents),con))


#함수
def sum(a,b):
  return a+b

x = 10.0
y = 20.0
print("%.1f + %.1f = %.1f" %(x,y,sum(x,y)))


#리스트
a = []
b = [1,2,3]
c = ["Hello",",","world"]
d = [1,2,3,"x","y","z"]
x = []

print(x)
x.append('a')
print(x)

x.append(123)
print(x)

x.append(["a","b"])
print(x)

#딕셔너리
dic = dict()
dic["name"] = "Heekyung"
dic["town"] = "Goyang city"
dic["job"] = "Assistant professor"
print(dic)

#클래스
class Student:
  def __init__(self,name):
    self.name = name

  def study(self, hard = False):
    if hard:
      print("%s 학생은 열심히 공부합니다" %self.name)
    else:
      print("%s 학생은 공부합니다." %self.name)

s = Student('Heekyung')
s.study()
s.study(hard = True)

Hello, World
정수: 3, 03, 003, 0003, 00003
실수: 256, 256.1, 256.12
문자열:[Hello Word]
Regression 은(는) 기계학습 내용입니다
Classification 은(는) 기계학습 내용입니다
SVM 은(는) 기계학습 내용입니다
Clustering 은(는) 기계학습 내용입니다
Dimension reduction 은(는) 심측학습 내용입니다
NN 은(는) 심측학습 내용입니다
CNN 은(는) convolutional neural network 입니다
AE 은(는) 심측학습 내용입니다
GAN 은(는) 심측학습 내용입니다
RNN 은(는) 심측학습 내용입니다
[0/10] : Regression
[1/10] : Classification
[2/10] : SVM
[3/10] : Clustering
[4/10] : Dimension reduction
[5/10] : NN
[6/10] : CNN
[7/10] : AE
[8/10] : GAN
[9/10] : RNN
10.0 + 20.0 = 30.0
[]
['a']
['a', 123]
['a', 123, ['a', 'b']]
{'name': 'Heekyung', 'town': 'Goyang city', 'job': 'Assistant professor'}
Heekyung 학생은 공부합니다.
Heekyung 학생은 열심히 공부합니다


In [ ]:
#2.벡터, 행렬 연산, 그래프 그리기
import numpy as np

def print_val(x):
  print("Type:",type(x))
  print("Shape:",x.shape)
  print("값\n",x)
  print(" ")

#Rank 1 Np Array
x = np.array([1,2,3])
print_val(x)

x[0] = 5
print_val(x)

#Rank 2 Np Array
y = np.array([[1,2,3],[4,5,6]])
print_val(y)

#Rank 2 Zeros
a = np.zeros((2,2))
print_val(a)

#Rank 2 Ones
a = np.ones((3,2))
print_val(a)

#Rank2 단위 행렬(Identity Matrix)
a = np.eye(3,3)
print_val(a)

#Random Matrix(uniform: 0~1 사이 모든 값들이 나올 확률이 같음)
a = np.random.random((4,4))
print_val(a)

#Random Matrix(Gaussian:0을 평균으로 하는 가우시안 분포를 따르는 랜덤값)
a = np.random.randn(4,4)
print_val(a)

#Np Array Indexing
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print_val(a)
b = a[:2, 1:3]
print_val(b)

#행렬의 n번째 행 얻기
row1 = a[1,:]
print_val(row1)


#행렬의 원소별 연산:
m1 = np.array([[1,2],[3,4]], dtype = np.float64)
m2 = np.array([[5,6],[7,8]], dtype = np.float64)

#elementwise sum
print_val(m1+m2)
print_val(np.add(m1,m2))

#elementwise difference
print_val(m1-m2)
print_val(np.subtract(m1,m2))

#elementwise product
print_val(m1*m2)
print_val(np.multiply(m1,m2))

#elementwise division
print_val(m1/m2)
print_val(np.divide(m1,m2))

#elementwise square root
print_val(np.sqrt(m1))



#행렬 연산
m1 =  np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])
v1 = np.array([9,10])
v2 = np.array([11,12])

print_val(m1)
print_val(m2)
print_val(v1)
print_val(v2)

#벡터-벡터 연산
print_val(v1.dot(v2))
print_val(np.dot(v1,v2))

#Vector-Matrix 연산
print_val(m1.dot(v1))
print_val(np.dot(m1,v1))

#Matrix-Matrix 연산
print_val(m1.dot(m2))
print_val(np.dot(m1,m2))

#전치 행렬(Tranpose)
print_val(m1)
print_val(m1.T)

print_val(np.sum(m1)) #행렬의 모든 원소의 합
print_val(np.sum(m1, axis = 0)) #shape[0] (행)을 압축시키자, (2,2) -> (2,)
print_val(np.sum(m1, axis = 1)) #shape[1] (열)을 압축시키자. (2,2) ->(2,)


m1 = np.arrayp([[1,2,3],[4,5,6]])
print(m1)
print(m1.shape)
print(np.sum(m1))
print(np.sum(m1,axis = 0))
print(np.sum(m1, axis = 1))

#Zeros-like
m1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
m2 = np.zeros_like(m1) #m1과 같은 형태의 0으로 이루어진 np array 만들기

print_val(m1)
print_val(m2)

#MatPlot library
import matplotlib.pyplot as plt
%matplotlib inline

x = np.arange(0,10,0.1) #0~10까지 0.1 간격의 숫자 배열
y = np.sin(x)

plt.plot(x,y)

#한번에 두개의 그래프 그리기
y_sin = np.sin(x)
y_cos = np.cos(x)
plt.plot(x,y_sin)
plt.plot(x,y_cos)
plt.xlable('x axis label')
plt.ylabel('y axis label')
plt.title('sin ans cos')
plt.legend(['sin','cos'])

plt.show()

#Subplot
plt.subplot(2,1,1) #(2,1)형태의 플롯의 첫 번째 자리에 그리는 경우
plt.plot(x,y_sin)
plt.title('sin')

plt.subplot(2,1,2)
plt.plot(x,y_cos)
plt.title('cos')

plt.show()



Type: <class 'numpy.ndarray'>
Shape: (3,)
값
 [1 2 3]
 
Type: <class 'numpy.ndarray'>
Shape: (3,)
값
 [5 2 3]
 
Type: <class 'numpy.ndarray'>
Shape: (2, 3)
값
 [[1 2 3]
 [4 5 6]]
 
Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값
 [[0. 0.]
 [0. 0.]]
 
Type: <class 'numpy.ndarray'>
Shape: (3, 2)
값
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
 
Type: <class 'numpy.ndarray'>
Shape: (3, 3)
값
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
